### ISSUE TITLE
Design abstraction layer for multi-version protocols

### ISSUE THREAD

**Issue by TimoGlastra** [animo/aries-mobile-sdk#20]
With the addition of a lot of AIP 2.0 protocols, we're having multiple protocols that can have the same outcome. E.g. the connection and did exchange protocols both produce a connection record. We should look at an abstraction layer that takes away the complexity of dealing with multiple protocols from the user.

Protocols to look at: 

 - [ ] Issue Credential V2
 - [ ] Present Proof V2
 - [ ] Out-of-band / DID Exchange

## TODO

 - [ ] Write out interfaces for Present Proof (@karimStekelenburg)
 - [ ] Write out interface for Credential Record (@TimoGlastra)

## Questions

- Should we create new modules and records for the new protocols versions? (rather not!)
- How can we make the API for using a v1 or v2 version of the protocols as simple as possible 
	- ideally only specifying e.g. `protocolVersion: IssueCredential.v1`
	- Making sure the user doesn't have to deal with `CredentialRecord` and `CredentialRecordV2`.
	- Example 
	- (idea) what if we create a **new** record type for v2 (or other versions) that we move all v1 records to. Although a completely different message structure and possible content, v2 is mostly an extension to what was already possible in v1.
	- Example of abstracting v1 and v2: https://github.com/didx-xyz/aries-cloudapi-python/pull/114

```typescript
await agent.credentials.offerCredential(connectionId, {
	protocolVersion: IssueCredential.v2,
	credentialTypes: {
		indy: {
			credentialDefintionId: "xxx",
		},
		vc: {
			"@type": []
			// other vc stuff
		}
	}
})
```

Or we could even go completely into the w3c structure for the api, deriving the indy structure from it, but I'm not sure if that's the way to go.

```jsonc
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",  // ← required by VC spec
    // ↓ defines primaryProof, nonRevocationProof, aggregateProof — common to all VPs derived from safe creds
    "https://github.com/hyperledger/ursa/libzmix/docs/safecreds-context-v1.9.jsonld",
  ],
  "type": "VerifiablePresentation", // ← required by VC spec
  "verifiableCredential": [
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",  // ← required by VC spec
        // ↓ proof req schema; could be URI, DID URI, inlined, or DIDComm msg URI. For now, prefer inline.
        "did:sov:NcYxiDXkpYi6ov5FcYDi1;version-id=abcxyz"
      ],
      "type": [
        "VerifiableCredential",  // ← required by VC spec 
        "DerivedFromZKP" //  ← hardcoded by Indy; from safecreds-context
      ],
      "credentialSchema": {
        "id": "NcYxicryxQocYDi1e:2:gvt:1.0:TAG_1", // ← id of credential definition
        "type": "DerivedSchema" //  ← hardcoded by Indy; from safecreds-context
      },
      "issuer": "did:example:Wz4eUg7SetGfaUVCn8U9d62oDYrUJLuUtcy619", // ← looked up from cred def
      "issuanceDate": "2020-07-25T18:23:17.492Z", // ← random val before cred was derived (NOT from source)
      "credentialSubject": [{ //  ← array optional but always used to support multiple subjects
        "name": "Alex", // ← disclosed from primary_proof.eq_proof.revealed_attrs
        "height_cm": 175, // ← disclosed from primary_proof.eq_proof.revealed_attrs
        "predicate_age_GE_18": true // ← ????
      }],
      "proof": {
        "type": "AnonCredDerivedCredentialv1", // ← suggest name change to “SafeVCProofv1”
        "primaryProof": "cg7wLNSi48K5qNyAVMv1Ur8i...cSAsym2sgSk737", // ← base58 of primary_proof
        "nonRevocationProof": "mu6fg2JPU1HvSXsf...RSce53M6UwQCxYs3d2h" // ← base58 of non_revoc_proof
      }
  }],
  "proof": {
    "type": "SafeVPProof-v1", // ← hardcoded by Indy (first cut had “AnonCredPresentationProofv1”)
    "aggregateProof": "DgYdYMUYHUCEY5u5fK...j915Lt3hMzLHoPiPQ9sSVfRrs1D" // ← base58 of aggregated_proof
  }
}
```

**Comment by karimStekelenburg** [comment]
Here is a possible design of the `offerCredential` public API.

The idea is **not** to create two separate methods for `issue-credential` v1 and v2, but offer a single method that allows for issuance using both protocol versions. For this reason we have a `protocolVersion` attribute, as @TimoGlastra had already proposed. 

If the `protocolVersion` is set to `1`, the `credentialFormats` object **must** contain the `indy` object. If the `linkedDataProof` object is also provided, it will be ignored as it's not supported by `v1`.

If `protocolVersion` is set to `2`, then at least one of the formats must be provided. If both the `indy` and `linkedDataProof` formats are provided, the caller must make sure the two formats represent the same credential.

A `offerCredential` call for `issue-credential v2` would then look something like this:

```typescript
await agent.credentials.offerCredential({
  connectionId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  protocolVersion: 2,
  comment: "Some thoughts...",
  autoAcceptCredential: "contentApproved",
  credentialFormats: {
    indy: {
      credentialDefinitionId: "WgWxqztrNooG92RXvxSTWv:3:CL:20:tag",
      preview: {
        "@type": "issue-credential/2.0/credential-preview",
        attributes: [
          {
            "mime-type": "text/plain",
            "name": "givenName",
            "value": "JOHN"
          },
          {
            "mime-type": "text/plain",
            "name": "familyName",
            "value": "SMITH"
          },
          {
            "mime-type": "text/plain",
            "name": "gender",
            "value": "Male"
          },
        ]
      }
    },
    linkedDataProof: {
      credential: {
        "@context": [
          "https://www.w3.org/2018/credentials/v1",
          "https://w3id.org/citizenship/v1"
        ],
        credentialSubject: {
          familyName: "SMITH",
          gender: "Male",
          givenName: "JOHN",
          type: [
            "PermanentResident",
            "Person"
          ]
        },
        description: "Government of Example Permanent Resident Card.",
        identifier: "83627465",
        issuanceDate: "2019-12-03T12:19:52Z",
        issuer: "did:key:z6MkmjY8GnV5i9YTDtPETC2uUAW6ejw3nk5mXF5yci5ab7th",
        name: "Permanent Resident Card",
        type: [
          "VerifiableCredential",
          "PermanentResidentCard"
        ]
      },
      options: {
        "proofType": "Ed25519Signature2018"
      }
    } 
  }
})
```
