### ISSUE TITLE
Design the public API of the Aries Mobile SDK

### ISSUE THREAD

**Issue by TimoGlastra** [animo/aries-mobile-sdk#25]
## Context

We want the SDK to be as easy as possible to use. This means also taking a good look at the current API of AFJ and see if we can make improvements. Especially the addition of all new protocols requires taking a good look at the API.

Example from the proposal (we definitely don't want to use this, but to get the conversation started)
![image](https://user-images.githubusercontent.com/23165168/135532989-341f69d2-bbb4-4f27-8195-0673d88a2d03.png)

## TODO

- [ ] Determine what modules the public API will consist of
	- connections
	- credentials
	- proofs
	- routing
	- did
	- ledger? (maybe belongs more as part of another module)
	- ...
- [ ] Design the public API for all modules
- [ ] Make sure the API is consistent across modules
