### ISSUE TITLE
Determine changes we need to make to external dependencies to run in react native

### ISSUE THREAD

**Issue by TimoGlastra** [animo/aries-mobile-sdk#34]
# TODO

- [ ] https://github.com/animo/aries-mobile-sdk/issues/33
- [ ] https://github.com/animo/aries-mobile-sdk/issues/32
- [ ] Reach out to Sphereon to ask about their experience with VCs in RN
	- Which signature suites do they support
	- Why they went with a fork over contributing back to the Digital Bazaar libraries?
- [ ] Reach out to Digitaal Bazaar to ask about their experience with VCs in RN
	- What is still needed to support RN (and get it merged)
	- Are there already signature suites supported in react native?
- [ ] Reach out to transmute to ask about the support of RN for their libraries
	- [ ] Is this something they're willing to support?
	- [ ] What will the required effort be to support RN?

![image](https://user-images.githubusercontent.com/23165168/136386797-54c1fb5c-2e67-408c-8f9f-961f2ea6b856.png)

# Context

### Transmute VC libraries

https://github.com/transmute-industries/verifiable-data

From what I can tell RN is not supported. There are definitely dependencies that don't work in RN so we would need to determine the scope of required changes.

### Digital Bazaar VC libraries

https://github.com/digitalbazaar/vc-js

RN not supported out of the box, but they have React Native branches for the main repos. From a comment 17 days ago they're stuck in discussion:

> Stuck in discussion, with regards to what we're doing with TypeScript and ReactNative, across our libs.

If initial RN support is already there this may be a good set of libraries to use. They already have Node.JS and browser support, so we may need to put in a bit of effort to finish the RN support.

Downside to me about the Digital Bazaar libraries is that they're not using TypeScript for their packages. IMO for a library that plays such an essential role in the framework and we probably have to make contributions to in the future not having a TypeScript codebase feels like a burden. But as the comment above suggests, they're having discussions about it.

- https://github.com/digitalbazaar/vc-js/tree/rn
- https://github.com/digitalbazaar/credentials-context/tree/nofs
- https://github.com/digitalbazaar/jsonld.js/tree/rn
- https://github.com/digitalbazaar/http-client/tree/noesm
- https://github.com/digitalbazaar/rdf-canonize/tree/rn (https://github.com/digitalbazaar/rdf-canonize/pull/43)
- https://github.com/digitalbazaar/jsonld-signatures/tree/rn (https://github.com/digitalbazaar/jsonld-signatures/pull/142)

### Sphereon VC libraries

https://github.com/Sphereon-Opensource/rn-vc-js

The Sphereon VC libraries are a fork of the Digital Bazaar VC libraries. The name contains RN explicitly so I'm not sure if they are ditching the browser and Node.JS support. I'm a bit hesitant of adopting a fork, especially if Digital Bazaar is already working on RN support.

They do however have some signature suites specifically for RN that I haven't seen yet for Digital Bazaar. I think initially we're interested in Ed25519Signature2018 and the BBS+ 2020 signature suites.

- https://github.com/Sphereon-Opensource/rn-vc-js
- https://github.com/Sphereon-Opensource/rn-jsonld-signatures
- https://github.com/Sphereon-Opensource/rn-w3c-credentials-context
- https://github.com/Sphereon-Opensource/rn-ecdsa-secp256k1-signature-2019
- https://github.com/Sphereon-Opensource/rn-jws-linked-data-signature
- https://github.com/Sphereon-Opensource/rn-ecdsa-secp256k1-verification-key-2019
