### ISSUE TITLE
Determine how to automatically build binaries of Askar, CredX and VDR for iOS and Android

### ISSUE THREAD

**Issue by TimoGlastra** [animo/aries-mobile-sdk#47]
All native libraries already have a build pipeline to build for macOS, Windows and Linux. We need to determine how to build binaries for iOS and Android, and add a Github Actions pipeline to the respective repos to automatically build the binaries.

Do we need to build a framework for iOS? Or is that not needed because we are only accessing the libraries from c++?
Do we need to build an aar or something for Android? Which architectures do we need to support?

## TODO

- [ ] Determine how to build native binaries for iOS
- [ ] Determine how to build native binaries for Android
- [ ] Write Actions Pipeline for Indy VDR that build builds both iOS and Android binaries
- [ ] Write Actions Pipeline for Aries Askar that build builds both iOS and Android binaries
- [ ] Write Actions Pipeline for Indy CredX that build builds both iOS and Android binaries
- [ ] Make sure you can run it on a simulator for both iOS and Android!
- [ ] Reach out to GlobalID, I think they already have wrappers for Swift / Kotlin, which means they already did the work
